@login @smoke
Feature: HyperTest Sample
	As a user I want to test negative login

	@unsuccessfulLogin1 @todo @prateek @singh
	Scenario: Long Testcase
		Then practice on E-commerce http://tutorialsninja.com/demo/
		Then practice selenium http://www.practiceselenium.com/welcome.html
	    Then WebdriverPractice page http://webdriveruniversity.com/Contact-Us/contactus.html
		Then I am at ToolBox Practice page https://demoqa.com
		Then I am on https://www.google.com/ncr
		When I fill in "q" found by "name" with "Lambdatest"
		And I submit
		Then I should see title "Lambdatest - Google Search"
		Then I am on https://www.google.com/ncr
		When I fill in "q" found by "name" with "HyperTest"
		And I submit
		Then I should see title "HyperTest - Google Search"
		Then I am on https://www.google.com/ncr
		When I fill in "q" found by "name" with "Microsoft Azure"
		And I submit
		Then I should see title "Microsoft Azure - Google Search"
		Then I am on https://lambdatest.github.io/sample-todo-app/
		When I click on first item
		When I click on second item
		When I add new item "New item 1 to the list"
		Then I should see new item in list "New item 1 to the list"
		When I add new item "New item 2 to the list"
		Then I should see new item in list "New item 2 to the list"
		When I add new item "New item 3 to the list"
		Then I should see new item in list "New item 3 to the list"
		When I add new item "New item 4 to the list"
		Then I should see new item in list "New item 4 to the list"
		When I add new item "New item 5 to the list"
		Then I should see new item in list "New item 5 to the list"
		When I add new item "New item 6 to the list"
		Then I should see new item in list "New item 6 to the list"
		When I add new item "New item 7 to the list"
		Then I should see new item in list "New item 7 to the list"
		When I add new item "New item 8 to the list"
		Then I should see new item in list "New item 8 to the list"
		When I add new item "New item 9 to the list"
		Then I should see new item in list "New item 9 to the list"
		When I add new item "New item 10 to the list"
		Then I should see new item in list "New item 10 to the list"
		When I add new item "New item 11 to the list"
		Then I should see new item in list "New item 11 to the list"
		When I add new item "New item 12 to the list"
		Then I should see new item in list "New item 12 to the list"
		When I add new item "New item 13 to the list"
		Then I should see new item in list "New item 13 to the list"
		When I add new item "New item 14 to the list"
		Then I should see new item in list "New item 14 to the list"
		When I add new item "New item 15 to the list"
		Then I should see new item in list "New item 15 to the list"
		When I add new item "New item 16 to the list"
		Then I should see new item in list "New item 16 to the list"
		When I add new item "New item 17 to the list"
		Then I should see new item in list "New item 17 to the list"
		When I add new item "New item 18 to the list"
		Then I should see new item in list "New item 18 to the list"
		When I add new item "New item 19 to the list"
		Then I should see new item in list "New item 19 to the list"
		When I add new item "New item 20 to the list"
		Then I should see new item in list "New item 20 to the list"
		When I add new item "New item 21 to the list"
		Then I should see new item in list "New item 21 to the list"
		When I add new item "New item 22 to the list"
		Then I should see new item in list "New item 22 to the list"
		When I add new item "New item 23 to the list"
		Then I should see new item in list "New item 23 to the list"
		When I add new item "New item 24 to the list"
		Then I should see new item in list "New item 24 to the list"
		When I add new item "New item 25 to the list"
		Then I should see new item in list "New item 25 to the list"
		When I add new item "New item 26 to the list"
		Then I should see new item in list "New item 26 to the list"
		When I add new item "New item 27 to the list"
		Then I should see new item in list "New item 27 to the list"
		When I add new item "New item 28 to the list"
		Then I should see new item in list "New item 28 to the list"
		When I add new item "New item 29 to the list"
		Then I should see new item in list "New item 29 to the list"
		When I add new item "New item 30 to the list"
		Then I should see new item in list "New item 30 to the list"
		When I add new item "New item 31 to the list"
		Then I should see new item in list "New item 31 to the list"
		When I add new item "New item 32 to the list"
		Then I should see new item in list "New item 32 to the list"
		When I add new item "New item 33 to the list"
		Then I should see new item in list "New item 33 to the list"
		When I add new item "New item 34 to the list"
		Then I should see new item in list "New item 34 to the list"
		When I add new item "New item 35 to the list"
		Then I should see new item in list "New item 35 to the list"
		When I add new item "New item 36 to the list"
		Then I should see new item in list "New item 36 to the list"
		When I add new item "New item 37 to the list"
		Then I should see new item in list "New item 37 to the list"
		When I add new item "New item 38 to the list"
		Then I should see new item in list "New item 38 to the list"
		When I add new item "New item 39 to the list"
		Then I should see new item in list "New item 39 to the list"
		When I add new item "New item 40 to the list"
		Then I should see new item in list "New item 40 to the list"
		When I add new item "New item 41 to the list"
		Then I should see new item in list "New item 41 to the list"
		When I add new item "New item 42 to the list"
		Then I should see new item in list "New item 42 to the list"
		When I add new item "New item 43 to the list"
		Then I should see new item in list "New item 43 to the list"
		When I add new item "New item 44 to the list"
		Then I should see new item in list "New item 44 to the list"
		When I add new item "New item 45 to the list"
		Then I should see new item in list "New item 45 to the list"
		When I add new item "New item 46 to the list"
		Then I should see new item in list "New item 46 to the list"
		When I add new item "New item 47 to the list"
		Then I should see new item in list "New item 47 to the list"
		When I add new item "New item 48 to the list"
		Then I should see new item in list "New item 48 to the list"
		When I add new item "New item 49 to the list"
		Then I should see new item in list "New item 49 to the list"
		When I add new item "New item 50 to the list"
		Then I should see new item in list "New item 50 to the list"
		When I add new item "New item 51 to the list"
		Then I should see new item in list "New item 51 to the list"
		When I add new item "New item 52 to the list"
		Then I should see new item in list "New item 52 to the list"
		When I add new item "New item 53 to the list"
		Then I should see new item in list "New item 53 to the list"
		When I add new item "New item 54 to the list"
		Then I should see new item in list "New item 54 to the list"
		When I add new item "New item 55 to the list"
		Then I should see new item in list "New item 55 to the list"
		When I add new item "New item 56 to the list"
		Then I should see new item in list "New item 56 to the list"
		When I add new item "New item 57 to the list"
		Then I should see new item in list "New item 57 to the list"
		When I add new item "New item 58 to the list"
		Then I should see new item in list "New item 58 to the list"
		When I add new item "New item 59 to the list"
		Then I should see new item in list "New item 59 to the list"
		When I add new item "New item 60 to the list"
		Then I should see new item in list "New item 60 to the list"
		When I add new item "New item 61 to the list"
		Then I should see new item in list "New item 61 to the list"
		When I add new item "New item 62 to the list"
		Then I should see new item in list "New item 62 to the list"
		When I add new item "New item 63 to the list"
		Then I should see new item in list "New item 63 to the list"
		When I add new item "New item 64 to the list"
		Then I should see new item in list "New item 64 to the list"
		When I add new item "New item 65 to the list"
		Then I should see new item in list "New item 65 to the list"
		When I add new item "New item 66 to the list"
		Then I should see new item in list "New item 66 to the list"
		When I add new item "New item 67 to the list"
		Then I should see new item in list "New item 67 to the list"
		When I add new item "New item 68 to the list"
		Then I should see new item in list "New item 68 to the list"
		When I add new item "New item 69 to the list"
		Then I should see new item in list "New item 69 to the list"
		When I add new item "New item 70 to the list"
		Then I should see new item in list "New item 70 to the list"
		When I add new item "New item 71 to the list"
		Then I should see new item in list "New item 71 to the list"
		When I add new item "New item 72 to the list"
		Then I should see new item in list "New item 72 to the list"
		When I add new item "New item 73 to the list"
		Then I should see new item in list "New item 73 to the list"
		When I add new item "New item 74 to the list"
		Then I should see new item in list "New item 74 to the list"
		When I add new item "New item 75 to the list"
		Then I should see new item in list "New item 75 to the list"
		When I add new item "New item 76 to the list"
		Then I should see new item in list "New item 76 to the list"
		When I add new item "New item 77 to the list"
		Then I should see new item in list "New item 77 to the list"
		When I add new item "New item 78 to the list"
		Then I should see new item in list "New item 78 to the list"
		When I add new item "New item 79 to the list"
		Then I should see new item in list "New item 79 to the list"
		When I add new item "New item 80 to the list"
		Then I should see new item in list "New item 80 to the list"
		When I add new item "New item 81 to the list"
		Then I should see new item in list "New item 81 to the list"
		When I add new item "New item 82 to the list"
		Then I should see new item in list "New item 82 to the list"
		When I add new item "New item 83 to the list"
		Then I should see new item in list "New item 83 to the list"
		When I add new item "New item 84 to the list"
		Then I should see new item in list "New item 84 to the list"
		When I add new item "New item 85 to the list"
		Then I should see new item in list "New item 85 to the list"
		When I add new item "New item 86 to the list"
		Then I should see new item in list "New item 86 to the list"
		When I add new item "New item 87 to the list"
		Then I should see new item in list "New item 87 to the list"
		When I add new item "New item 88 to the list"
		Then I should see new item in list "New item 88 to the list"
		When I add new item "New item 89 to the list"
		Then I should see new item in list "New item 89 to the list"
		When I add new item "New item 90 to the list"
		Then I should see new item in list "New item 90 to the list"
		When I add new item "New item 91 to the list"
		Then I should see new item in list "New item 91 to the list"
		When I add new item "New item 92 to the list"
		Then I should see new item in list "New item 92 to the list"
		When I add new item "New item 93 to the list"
		Then I should see new item in list "New item 93 to the list"
		When I add new item "New item 94 to the list"
		Then I should see new item in list "New item 94 to the list"
		When I add new item "New item 95 to the list"
		Then I should see new item in list "New item 95 to the list"
		When I add new item "New item 96 to the list"
		Then I should see new item in list "New item 96 to the list"
		When I add new item "New item 97 to the list"
		Then I should see new item in list "New item 97 to the list"
		When I add new item "New item 98 to the list"
		Then I should see new item in list "New item 98 to the list"
		When I add new item "New item 99 to the list"
		Then I should see new item in list "New item 99 to the list"
		When I add new item "New item 100 to the list"
		Then I should see new item in list "New item 100 to the list"
